#
# Makefile
#

OBJS	= main.o kernel.o

LIBS	= $(CIRCLE_PATH)/lib/usb/libusb.a \
	  $(CIRCLE_PATH)/lib/input/libinput.a \
	  $(CIRCLE_PATH)/lib/fs/libfs.a \
	  $(CIRCLE_PATH)/lib/libcircle.a

include $(CIRCLE_PATH)/Rules.mk
