#!/bin/bash

cd lib
cd core

make $1 $2 || exit
cd ..

# TODO: Add new libs here
#cd subdir
#make $1 $2 || exit
#cd ..

cd ..

cd main
make $1 $2 || exit
cd ..

# TODO: Add new apps here
#cd subdir
#make $1 $2 || exit
#cd ..
