/*
 * This file is subject to the terms of the GFX License. If a copy of
 * the license was not distributed with this file, you can obtain one at:
 *
 *              http://ugfx.org/license.html
 */


#include "lvgl/lv_core/lv_group.c"
#include "lvgl/lv_core/lv_indev.c"
#include "lvgl/lv_core/lv_obj.c"
#include "lvgl/lv_core/lv_refr.c"
#include "lvgl/lv_core/lv_style.c"
#include "lvgl/lv_core/lv_vdb.c"

#include "lvgl/lv_draw/lv_draw_vbasic.c"
#include "lvgl/lv_draw/lv_draw.c"
#include "lvgl/lv_draw/lv_draw_rbasic.c"

#include "lvgl/lv_hal/lv_hal_disp.c"
#include "lvgl/lv_hal/lv_hal_indev.c"
#include "lvgl/lv_hal/lv_hal_tick.c"

#include "lvgl/lv_misc/lv_font.c"
#include "lvgl/lv_misc/lv_circ.c"
#include "lvgl/lv_misc/lv_area.c"
#include "lvgl/lv_misc/lv_task.c"
#include "lvgl/lv_misc/lv_fs.c"
#include "lvgl/lv_misc/lv_anim.c"
#include "lvgl/lv_misc/lv_mem.c"
#include "lvgl/lv_misc/lv_ll.c"
#include "lvgl/lv_misc/lv_color.c"
#include "lvgl/lv_misc/lv_txt.c"
#include "lvgl/lv_misc/lv_ufs.c"
#include "lvgl/lv_misc/lv_trigo.c"
#include "lvgl/lv_misc/lv_fonts/dejavu_40_cyrillic.c"
#include "lvgl/lv_misc/lv_fonts/dejavu_40_latin_ext_a.c"
#include "lvgl/lv_misc/lv_fonts/dejavu_40_latin_ext_b.c"
#include "lvgl/lv_misc/lv_fonts/dejavu_40_sup.c"
#include "lvgl/lv_misc/lv_fonts/dejavu_40.c"
#include "lvgl/lv_misc/lv_fonts/symbol_40_file.c"
#include "lvgl/lv_misc/lv_fonts/symbol_40_feedback.c"
#include "lvgl/lv_misc/lv_fonts/symbol_40_basic.c"

#include "lvgl/lv_objx/lv_bar.c"
#include "lvgl/lv_objx/lv_cb.c"
#include "lvgl/lv_objx/lv_ddlist.c"
#include "lvgl/lv_objx/lv_kb.c"
#include "lvgl/lv_objx/lv_ta.c"
#include "lvgl/lv_objx/lv_line.c"
#include "lvgl/lv_objx/lv_mbox.c"
#include "lvgl/lv_objx/lv_roller.c"
#include "lvgl/lv_objx/lv_tabview.c"
#include "lvgl/lv_objx/lv_btn.c"
#include "lvgl/lv_objx/lv_chart.c"
#include "lvgl/lv_objx/lv_gauge.c"
#include "lvgl/lv_objx/lv_label.c"
#include "lvgl/lv_objx/lv_list.c"
#include "lvgl/lv_objx/lv_slider.c"
#include "lvgl/lv_objx/lv_btnm.c"
#include "lvgl/lv_objx/lv_cont.c"
#include "lvgl/lv_objx/lv_img.c"
#include "lvgl/lv_objx/lv_led.c"
#include "lvgl/lv_objx/lv_lmeter.c"
#include "lvgl/lv_objx/lv_page.c"
#include "lvgl/lv_objx/lv_sw.c"
#include "lvgl/lv_objx/lv_win.c"

#include "lvgl/lv_themes/lv_theme_alien.c"
#include "lvgl/lv_themes/lv_theme.c"
#include "lvgl/lv_themes/lv_theme_default.c"
#include "lvgl/lv_themes/lv_theme_night.c"
#include "lvgl/lv_themes/lv_theme_templ.c"
#include "lvgl/lv_themes/lv_theme_zen.c"
#include "lvgl/lv_themes/lv_theme_material.c"
